# Paths
FABULOUS_ROOT = ../../macro/sky130A/fabulous
EXTRA_PRIMITIVES_PATH = ../extra_primitives.v
BIT_GEN = ../bit_gen.py
BIT_TO_HEX = ../bit_to_hex.py

# Adjust sources
RTL = ../top_wrapper.v adc_dac.sv ../primitive_wrappers.v
TOP = top_wrapper
DESIGN_NAME = adc_dac

# Include base Makefile
include ../makefile.include
