# Paths
FABULOUS_ROOT = ../../macro/sky130A/fabulous
EXTRA_PRIMITIVES_PATH = ../extra_primitives.v
BIT_GEN = ../bit_gen.py

# Adjust sources
RTL = ../top_wrapper.v sram.sv ../primitive_wrappers.v
TOP = top_wrapper
DESIGN_NAME = sram

# Include base Makefile
include ../makefile.include
