# Paths
FABULOUS_ROOT = ../../macro/sky130A/fabulous
EXTRA_PRIMITIVES_PATH = ../extra_primitives.v
BIT_GEN = ../bit_gen.py

# Adjust sources
RTL = ../top_wrapper.v all_ones.v
TOP = top_wrapper
DESIGN_NAME = all_ones

# Include base Makefile
include ../makefile.include
