# Paths
FABULOUS_ROOT = ../../macro/sky130A/fabulous
EXTRA_PRIMITIVES_PATH = ../extra_primitives.v
BIT_GEN = ../bit_gen.py

# Adjust sources
RTL = ../top_wrapper.v top.sv $(wildcard rtl/*.sv) $(wildcard rtl/*.v) ../primitive_wrappers.v
TOP = top_wrapper
DESIGN_NAME = fazyrv

# Include base Makefile
include ../makefile.include
